### ISSUE TITLE
CF有多个组织时部署报错

### ISSUE THREAD

**Issue by DreamFerry** [ling-drag0n/CloudPaste-old#15]
我的Cloudflare账户链接了多个组织，在自动部署该项目时，发生了错误无法完成部署，错误信息如下：
```
✘ [ERROR] More than one account available but unable to select one in non-interactive mode.
  Please set the appropriate `account_id` in your Wrangler configuration file.
  Available accounts are (`<name>`: `<account_id>`):
```
虽然设置了CF_ACCOUNT_ID的环境变量，但仍然提示无法指定账户，麻烦作者排查一下，兼容这种情况

**Comment by ling-drag0n** [comment]
你试试修改一下deploy.yml文件最后的name: Deploy to Cloudflare Workers的env：
```yml
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy --var ADMIN_USERNAME:${{ secrets.ADMIN_USERNAME }} --var ADMIN_PASSWORD:${{ secrets.ADMIN_PASSWORD }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
```
